EE-737 validate_rule_data
yoyowallet/business-rules pull request #9
Opened 2017-02-15 16:09 UTC by gryevns

2017-02-15 16:27 UTC, aaronolszewski requested changes
I find the flow of the function `validate_conditions` quite hard to follow. Breaking it down into smaller functions would be nicer

2017-02-15 16:27 UTC, ShavedWheels commented on business_rules/utils.py
> +    def validate_conditions(input_conditions, rule_schema):
Can we break this function down into smaller functions? A lot going on here...

2017-02-15 16:27 UTC, ShavedWheels commented on business_rules/utils.py
> +                if len(keys) > 1:
What is so special about `1`?

2017-02-16 07:43 UTC, gryevns commented on business_rules/utils.py
> +                if len(keys) > 1:
If there is `any` or `all` then it only makes sense in business rules to have one key

2017-02-16 13:57 UTC, ipeluffo commented on business_rules/utils.py
> +            if item.get('name') == condition.get('name'):
What if there isn't any variable with the same name as the condition?
It seems that the function will return `None`

2017-02-16 14:06 UTC, ipeluffo commented on business_rules/utils.py
> +        engine._check_params_valid_for_method(method, params, method_type.METHOD_TYPE_VARIABLE)
I think it makes more sense to move this function into this module and reuse it from `engine` module.

2017-02-16 14:12 UTC, ipeluffo commented on tests/test_utils.py
> +            'all': [
I'd add an embedded condition, for example:
```python
{
  "conditions": {
    "any": [
      {
        "name": "current_inventory",
        "operator": "less_than",
        "value": 5
      },
      {
        "all": [
          {
            "name": "current_month",
            "operator": "equal_to",
            "value": "December"
          },
          {
            "name": "current_inventory",
            "operator": "less_than",
            "value": 20
          }
        ]
      }
    ]
  },
  "actions": {}
}
```

2017-02-16 17:28 UTC, gryevns commented on business_rules/utils.py
> +            if item.get('name') == condition.get('name'):
Already checked in `validate_condition_name`?

2017-02-16 17:30 UTC, gryevns commented on business_rules/utils.py
> +        engine._check_params_valid_for_method(method, params, method_type.METHOD_TYPE_VARIABLE)
👍

2017-02-16 17:32 UTC, gryevns commented on tests/test_utils.py
> +            'all': [
👍

2017-02-16 17:39 UTC, ipeluffo commented on business_rules/utils.py
> +            if item.get('name') == condition.get('name'):
it seems correct, but there is a dependency on the execution order of the two methods... 
Can you add a return value despite for the current implementation that should never happen?

2017-02-16 17:44 UTC, gryevns commented on business_rules/utils.py
> +            if item.get('name') == condition.get('name'):
done!

2017-02-16 17:44 UTC, ipeluffo approved these changes
👍

2017-02-16 17:52 UTC, ShavedWheels commented on business_rules/utils.py
>                      for k, v in input_conditions.iteritems():
I see that `k` is a throw away variable here. Is it not best practise (like I have seen in Platform) to use a `_` to explicitly show this?

2017-02-16 18:14 UTC, ShavedWheels commented on business_rules/utils.py
> +                    for k, v in input_conditions.iteritems():
I see that `k` is a throw away variable here. Is it not best practise (like I have seen everywhere n Platform) to use a `_` to explicitly show this?

2017-02-16 19:21 UTC, aaronolszewski approved these changes

2017-02-16 19:25 UTC, ShavedWheels commented on business_rules/utils.py
> +                    raise AssertionError('Expected ONE of "any" or "all" but found {}'.format(keys))
Do you not want the message to specify the quantity of keys? Here you will just return a list of the keys rather than the quantity `len(keys)`

2017-02-16 19:26 UTC, gryevns commented on business_rules/utils.py
> +                    raise AssertionError('Expected ONE of "any" or "all" but found {}'.format(keys))
yes **ONE**

2017-02-16 19:28 UTC, ShavedWheels commented on business_rules/utils.py
> +                    raise AssertionError('Expected ONE of "any" or "all" but found {}'.format(keys))
I mean in the formatting

2017-02-17 09:01 UTC, merged